"""
scenes.py — Scene description data model and loading utilities.

Phase 3 of the SpaceAmb pipeline introduces *scenes*: free-form textual
descriptions of fully articulated architectural spaces.  Where atoms are
single-word units and descriptors are 2–3-atom phrases, a scene is a
paragraph-length description that might be drawn from:

  * hand-authored design briefs
  * architectural programme statements
  * critic reviews or space descriptions
  * text generated by composing atoms and descriptors into sentences

Scenes are scored against the same space × ambiance query grid as atoms
and descriptors, using the identical embedding + cosine similarity pipeline.
This makes them directly comparable: you can ask "which atoms, descriptors,
and scenes best match 'relaxing living room'?" in a single ranked table.

Usage
-----
    from semantic_architecture.scenes import load_scenes, scenes_summary

    scenes = load_scenes("data/raw/scenes.json")
    print(scenes_summary(scenes))

Data format
-----------
``data/raw/scenes.json`` contains a top-level ``"scenes"`` array.  Each
entry must have ``id``, ``text``, ``space``, and ``ambiance`` fields.
The ``notes`` field is optional.

Example entry::

    {
      "id": "scene_relaxing_living_room_01",
      "text": "A sun-drenched living room with a deep sofa ...",
      "space": "living room",
      "ambiance": "relaxing",
      "notes": "Warm, soft domestic comfort"
    }

The ``space`` and ``ambiance`` fields record the *intended* target for each
scene — useful as ground truth when evaluating whether the scoring pipeline
ranks a scene highest for its intended query.  They are not used during
embedding or scoring.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional


# ------------------------------------------------------------------
# Data model
# ------------------------------------------------------------------

@dataclass
class Scene:
    """
    A free-form textual description of an architectural space.

    Attributes
    ----------
    id : str
        Unique identifier, e.g. ``"scene_relaxing_living_room_01"``.
    text : str
        The description that is embedded and scored.
    space : str
        The intended architectural program, e.g. ``"living room"``.
        Should match a value in ``programs.json``.
    ambiance : str
        The intended ambiance, e.g. ``"relaxing"``.
        Should match a value in ``ambiances.json``.
    notes : str or None
        Optional freeform annotation about the scene's character.
    """

    id: str
    text: str
    space: str
    ambiance: str
    notes: Optional[str] = None

    def __str__(self) -> str:
        return f"Scene({self.id!r}: {self.space!r} × {self.ambiance!r})"

    def __repr__(self) -> str:
        preview = self.text[:60] + "…" if len(self.text) > 60 else self.text
        return (
            f"Scene(id={self.id!r}, space={self.space!r}, "
            f"ambiance={self.ambiance!r}, text={preview!r})"
        )

    @property
    def intended_query(self) -> str:
        """Combined query text this scene was authored for."""
        return f"{self.ambiance} {self.space}"


# ------------------------------------------------------------------
# Loading
# ------------------------------------------------------------------

def load_scenes(path_or_paths: str | Path | List[str | Path]) -> List[Scene]:
    """
    Load scene descriptions from one or more JSON files.

    Parameters
    ----------
    path_or_paths : str, Path, or list of those
        Path(s) to JSON file(s) with a top-level ``"scenes"`` array.

    Returns
    -------
    list of Scene
    """
    if isinstance(path_or_paths, (str, Path)):
        paths = [Path(path_or_paths)]
    else:
        paths = [Path(p) for p in path_or_paths]

    scenes = []
    for path in paths:
        if not path.exists():
            continue
        with path.open(encoding="utf-8") as fh:
            data = json.load(fh)

        for entry in data.get("scenes", []):
            scenes.append(
                Scene(
                    id=entry["id"],
                    text=entry["text"],
                    space=entry["space"],
                    ambiance=entry["ambiance"],
                    notes=entry.get("notes"),
                )
            )
    return scenes


# ------------------------------------------------------------------
# Summary / diagnostics
# ------------------------------------------------------------------

def scenes_summary(scenes: List[Scene]) -> str:
    """
    Return a human-readable summary of the scene collection.

    Counts by space and ambiance; reports text length statistics.
    """
    if not scenes:
        return "No scenes loaded."

    space_counts = Counter(s.space for s in scenes)
    amb_counts   = Counter(s.ambiance for s in scenes)
    lengths      = [len(s.text) for s in scenes]

    lines = [
        f"Scenes loaded : {len(scenes)}",
        "",
        "By space:",
    ]
    for sp, n in sorted(space_counts.items()):
        lines.append(f"  {sp:<22}: {n}")

    lines += ["", "By ambiance:"]
    for amb, n in sorted(amb_counts.items()):
        lines.append(f"  {amb:<22}: {n}")

    lines += [
        "",
        f"Text length — min: {min(lengths)}, "
        f"mean: {sum(lengths)//len(lengths)}, "
        f"max: {max(lengths)} chars",
    ]
    return "\n".join(lines)


def validate_scenes(
    scenes: List[Scene],
    valid_spaces: Optional[List[str]] = None,
    valid_ambiances: Optional[List[str]] = None,
) -> List[str]:
    """
    Validate scene data against known programs and ambiances.

    Parameters
    ----------
    scenes : list of Scene
    valid_spaces : list of str or None
        If provided, warns about scenes whose ``space`` doesn't match.
    valid_ambiances : list of str or None
        If provided, warns about scenes whose ``ambiance`` doesn't match.

    Returns
    -------
    list of str
        Warning messages (empty if all scenes are valid).
    """
    warnings: List[str] = []

    # Check for duplicate IDs
    ids = [s.id for s in scenes]
    seen: set[str] = set()
    for sid in ids:
        if sid in seen:
            warnings.append(f"Duplicate scene id: {sid!r}")
        seen.add(sid)

    # Check for empty text
    for s in scenes:
        if not s.text.strip():
            warnings.append(f"Scene {s.id!r} has empty text.")

    # Check space and ambiance against known values
    if valid_spaces is not None:
        valid_sp_set = set(valid_spaces)
        for s in scenes:
            if s.space not in valid_sp_set:
                warnings.append(
                    f"Scene {s.id!r}: space {s.space!r} not in known programs."
                )

    if valid_ambiances is not None:
        valid_amb_set = set(valid_ambiances)
        for s in scenes:
            if s.ambiance not in valid_amb_set:
                warnings.append(
                    f"Scene {s.id!r}: ambiance {s.ambiance!r} not in known ambiances."
                )

    return warnings
